### PR TITLE
SLEP011: Add Logical Analysis of Data (LAD) classifier

### PR DESCRIPTION
**Pull request by GregoryMorse**
See the SLEP for details.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
I do not think that adding a classifier calls for a SLEP: SLEPs are for modifications that touch many classifiers.

It should rather be discussed in an issue in the scikit-learn repo.

However, I am not sure that the proposed algorithm meet the criteria for inclusion (listed on https://scikit-learn.org/stable/faq.html#what-are-the-inclusion-criteria-for-new-algorithms), indeed, a Google search shows only a few dozen citations:
https://scholar.google.ca/scholar?q=Accelerated+algorithm+for+pattern+detection+in+logical+analysis+of+data&hl=en&as_sdt=0&as_vis=1&oi=scholart

**Comment by chkoar** [comment]
A scikit-learn-contrib package maybe.

**Comment by GregoryMorse** [comment]
Okay there is definetely good information here.  But this algorithm might be worth it.  Take for example a more influential paper.  That paper  I cited is particularly useful for finding patterns efficiently but for the overall process: https://scholar.google.ca/scholar?hl=en&as_sdt=0%2C5&as_vis=1&q=An+implementation+of+logical+analysis+of+data&btnG=

An implementation of logical analysis of data
E Boros, PL Hammer, T Ibaraki, A Kogan
Cited by 430

At least I should focus on making a supporting argument based on the right paper, along with other requirements from the FAQ.  I was also unsure if a SLEP was the right place for the discussion.  For now probably a contrib package is the right direction and it can be considered for the main library thereafter.  Thanks to both of you for your guidance on this.

**Comment by GregoryMorse** [comment]
The only real question is wide use after studying the FAQ.  But I would consider that its wide use is partly because public open source implementations are not available.  Research demonstrates very good results with it.

**Comment by jnothman** [comment]
Which sounds like a good reason for it to be implemented in contrib
initially

**Comment by adrinjalali** [comment]
Also, it may be easier to have it in sklearn-extra instead of a stand-alone package.

**Pull request closed without merging**
