### PR TITLE
[MRG] Sphinx doc

### PR DESCRIPTION
**Pull request by NicolasHug**
I pulled all 4 current PRs and put them together with sphinx (RTD theme).

I can spin up a RTD project as well when / if this is merged.

### CODE REVIEW

**Comment by NicolasHug** [comment]
It works, but we have to use the full syntax i.e. 

    :class:`sklearn.pipeline.Pipeline`


The "easy" version with simple backticks does not work.

**Comment by amueller** [comment]
Did you use the same default role as in the sklearn repo?

**Comment by NicolasHug** [comment]
Oh yeah it works with `default_role = 'any'`

but now there's a lot of warnings 

<details>
```
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:154: WARNING: 'any' reference target not found: pipeline.named_steps['lasso'].coef_
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:158: WARNING: 'any' reference target not found: pipeline.steps[-1][1].coef_
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:226: WARNING: 'any' reference target not found: TransModifier
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:229: WARNING: 'any' reference target not found: X_new, y_new = estimator.fit_modify(X, y)
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:231: WARNING: 'any' reference target not found: X_new, y_new = estimator.trans_modify(X, y)
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:235: WARNING: 'any' reference target not found: X_new, y_new, sample_props = estimator.fit_modify(X, y)
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:237: WARNING: 'any' reference target not found: X_new, y_new, sample_props = estimator.trans_modify(X, y)
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:241: WARNING: 'any' reference target not found: fit_modify
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:241: WARNING: 'any' reference target not found: trans_modify
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:244: WARNING: 'any' reference target not found: fit_modify
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:263: WARNING: 'any' reference target not found: trans_modify
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:272: WARNING: 'any' reference target not found: cross_val_score
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:272: WARNING: 'any' reference target not found: GridSearchCV
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:290: WARNING: 'any' reference target not found: trans_modify
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:295: WARNING: 'any' reference target not found: trans_modify
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:295: WARNING: 'any' reference target not found: y_true
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:312: WARNING: 'any' reference target not found: sample_props
/home/nico/dev/enhancement_proposals/slep001/proposal.rst:315: WARNING: 'any' reference target not found: sample_props
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:91: WARNING: 'any' reference target not found: collections.OrderedDict
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:106: WARNING: 'any' reference target not found: steps
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:106: WARNING: 'any' reference target not found: Pipeline.steps
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:106: WARNING: 'any' reference target not found: list
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:106: WARNING: 'any' reference target not found: steps
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:106: WARNING: 'any' reference target not found: list
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:122: WARNING: 'any' reference target not found: None
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:131: WARNING: 'any' reference target not found: add
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:159: WARNING: 'any' reference target not found: (step, estimator)
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:197: WARNING: 'any' reference target not found: .steps
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:211: WARNING: 'any' reference target not found: replace()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:220: WARNING: 'any' reference target not found: rename()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:230: WARNING: 'any' reference target not found: pipeline.set_params()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:230: WARNING: 'any' reference target not found: subestimator.set_params()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:246: WARNING: 'any' reference target not found: del
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:266: WARNING: 'any' reference target not found: pop()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:285: WARNING: 'any' reference target not found: pop(step_name)
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:285: WARNING: 'any' reference target not found: popitem(step_name)
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:290: WARNING: 'any' reference target not found: Pipeline
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:293: WARNING: 'any' reference target not found: .fit
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:336: WARNING: 'any' reference target not found: pipe.add_*
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:424: WARNING: 'any' reference target not found: label_predictor
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:424: WARNING: 'any' reference target not found: ignore_predict
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:467: WARNING: 'any' reference target not found: __contains__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:467: WARNING: 'any' reference target not found: __getitem__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:467: WARNING: 'any' reference target not found: __setitem__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:467: WARNING: 'any' reference target not found: __delitem__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:468: WARNING: 'any' reference target not found: __len__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:468: WARNING: 'any' reference target not found: __iter__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:469: WARNING: 'any' reference target not found: __add__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:469: WARNING: 'any' reference target not found: __iadd__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:473: WARNING: 'any' reference target not found: get()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:473: WARNING: 'any' reference target not found: index()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:474: WARNING: 'any' reference target not found: extend()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:474: WARNING: 'any' reference target not found: insert()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:475: WARNING: 'any' reference target not found: keys()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:475: WARNING: 'any' reference target not found: items()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:475: WARNING: 'any' reference target not found: values()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:476: WARNING: 'any' reference target not found: clear()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:476: WARNING: 'any' reference target not found: pop()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:476: WARNING: 'any' reference target not found: popitem()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:476: WARNING: 'any' reference target not found: popfront()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:476: WARNING: 'any' reference target not found: popitemfront()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:481: WARNING: 'any' reference target not found: replace()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:482: WARNING: 'any' reference target not found: rename()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:490: WARNING: 'any' reference target not found: fromkeys()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:491: WARNING: 'any' reference target not found: setdefault()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:492: WARNING: 'any' reference target not found: sort()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:493: WARNING: 'any' reference target not found: __mul__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:493: WARNING: 'any' reference target not found: __rmul__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:493: WARNING: 'any' reference target not found: __imul__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:495: WARNING: 'any' reference target not found: AttributeError
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:495: WARNING: 'any' reference target not found: NotImplementedError
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:500: WARNING: 'any' reference target not found: __ge__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:500: WARNING: 'any' reference target not found: __gt__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:501: WARNING: 'any' reference target not found: __le__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:501: WARNING: 'any' reference target not found: __lt__()
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:507: WARNING: 'any' reference target not found: __getstate__
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:507: WARNING: 'any' reference target not found: picklier
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:509: WARNING: 'any' reference target not found: .steps
/home/nico/dev/enhancement_proposals/slep002/proposal.rst:551: WARNING: 'any' reference target not found: __init__
```
</details>

**Comment by amueller** [comment]
Can you check what we do in sklearn? I think we may have some plugin or configure a fall-back?
This seems to be a feature:
https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-any

possibly we should be using double backticks for code segments like ``X_new, y_new, sample_props = estimator.fit_modify(X, y)`` if we can't make it fall back to that.

Not sure why it throws a warning for ``cross_val_score`` though.

**Comment by NicolasHug** [comment]
I don't think we're doing anything in scikit learn for this.

Compiling the docs yields tons of `WARNING: 'any' reference target not found:`.

As far as I understand `any` really only cares about references. It's not about using double backticks vs single backticks. Single backticks are for refs (and using 'any' just makes it easier, without having to specify e.g. `:class:` or `:func:`), and double backticks are for code formatting.

**Comment by amueller** [comment]
My point was that if you use double backticks it'll just do code formatting and the any won't matter

**Comment by NicolasHug** [comment]
Yeah sure, I thought 'any' was introduced in sklearn so that we could use both simple and double backticks to format code (which I guess kinda works, expect that we get warnings?). I'm not sure.

Anyway, I used double backticks were appropriate, the only warning left is 

>enhancement_proposals/README.rst: WARNING: document isn't included in any toctree


Also, while intersphinx seems to be working properly, it doesn't look like we can write simply e.g. ``` `cross_val_score` ```. We need the full ``` `sklearn. ... .cross_val_score` ```. I think the only difference with/without 'any' is that we don't have to specify `:func:`

**Comment by amueller** [comment]
ok cool. I mean we don't need to polish everything in this PR imho and I'd be happy to merge.

**Comment by amueller** [comment]
> The idea is that valid SLEPs will get merged initially without review, and hence will be visible online, then will be revised in pull requests?

exactly, that's how numpy does it. The current PRs are getting too long and convoluted I think, and provide too little visibility.

**Comment by amueller** [comment]
Anyone else want to weight in? @ogrisel @GaelVaroquaux @agramfort ?

Maybe we want "accepted", "rejected", "in process" and "backlog" headers, with all the current ones in "backlog", simliar to:

https://www.numpy.org/neps/

The reason why I want a "backlog" is that I would like to enforce some timing constraints on the discussion but I don't want all of the backlog to come and haunt us once we enact the governance doc.

**Comment by agramfort** [comment]
I would prefer "under review" than "in process"

I am fine with backlog but maybe "late review" or "delayed review" ?

**Comment by amueller** [comment]
thanks. merging this, given the lack of feedback. we can always go back /fix stuff.

**Comment by amueller** [comment]
@NicolasHug can you spin up readthedocs (do you need to be an org member for that?) and add a link into the readme here?

**Pull request merged**
