### PR TITLE
use markdown for easier rendering.

### PR DESCRIPTION
**Pull request by amueller**
I think it might be easier to use markdown for SLEPs so we can directly use github pages instead of having to set up a sphinx build.
Open to other opinions of course.

### CODE REVIEW

**Comment by amueller** [comment]
Numpy uses rst, but they also use their main website / doc build to build their NEPs.

**Comment by amueller** [comment]
hm not entirely sure if this is actually better than sphinx, we'll see

**Comment by amueller** [comment]
I think I want intersphinx.

**Comment by jnothman** [comment]
Is there a good reason to not build this with the main docs?

**Comment by GaelVaroquaux** [comment]
> I think I want intersphinx.

Intersphinx rocks!!!

Interesting experiment that you're running. I am very interested in your
conclusion.

I love building webpages in pure jekyll with github pages, but I agree
that for technical stuff, I really like having the full sphinx artillery.

**Comment by amueller** [comment]
@jnothman the conclusion of the discussion on the governance doc was to have a separate repo. I don't know how we could have a separate repo and build them together.
I'm somewhat in favor of having it in the same repo for the exact reason to build them together but it seemed others preferred this solution. Happy to discuss again, though.

**Comment by amueller** [comment]
The main reason was to have notifications and git history not mixed up, I think (reason to keep repos separate, not to do separate builds)

**Pull request closed without merging**
