### PR TITLE
VOTE propose vote for SLEP007

### PR DESCRIPTION
**Pull request by glemaitre**
In this PR, I propose a vote for SLEP007.

As per our [governance](https://scikit-learn.org/stable/governance.html#decision-making-process), the vote will last 1 month and will be announced shortly on the internal mailing list. We will seek a consensus during this month. If no consensus is found, the decision will be escalated to the Technical Committee (TC).

### CODE REVIEW

**Comment by lorentzenchr** [comment]
+1

**Comment by jjerphan** [comment]
Just to clarify: my approval for this PR stands for a +1 for the vote.

**Comment by thomasjpfan** [comment]
+1 with minor adjustment to `verbose_feature_names_out` in `ColumnTransformer`: https://github.com/scikit-learn/enhancement_proposals/pull/60

**Comment by jnothman** [comment]
The SLEP says nothing of the types of the feature names or the collection of them. Should it? Otherwise, I'm happy with this.

(I have wondered, however, whether we give ourselves headaches by trying to ascribe names, rather than objects with structure and behaviour, to the representation of features. But certainly, we'd be giving ourselves more headaches if we wanted to attach such structured objects to DataFrames!)

**Comment by glemaitre** [comment]
> The SLEP says nothing of the types of the feature names (str vs other) or the collection of them (list vs array). 

This is probably something that we should clarify by amending the current proposal as done there: https://github.com/scikit-learn/enhancement_proposals/pull/59#issuecomment-956441998

**Comment by thomasjpfan** [comment]
Opened #61 to add more details regarding the container, dtype, and strings.

**Comment by glemaitre** [comment]
The vote has been open for a month and a consensus has been reached.
By our [decision-making process](https://scikit-learn.org/stable/governance.html#decision-making-process), I changed the status of this SLEP to "Accepted".

We can provide post-history changes to give more details and improve the current proposal.

ping @adrinjalali @thomasjpfan did I miss anything in the process? I let you review and merge this PR if everything is OK.

**Comment by adrinjalali** [comment]
I agree, and I think we've gone forward with the implementation and we seem to have a good consensus now.

**Pull request merged**
