### PR TITLE
[VOTE] Accept SLEP000

### PR DESCRIPTION
**Pull request by adrinjalali**
This PR is the place for us to vote for SLEP000: https://scikit-learn-enhancement-proposals.readthedocs.io/en/latest/slep000/proposal.html

It was discussed in depth in https://github.com/scikit-learn/enhancement_proposals/pull/30, but no unanimous consensus was achieved there.

Therefore here's the vote for us to see if it passes our majority. We require 2/3 of the cast vote (no quorum) to pass the SLEP.

The vote closes on 4th February 2021.

### CODE REVIEW

**Comment by NicolasHug** [comment]
I'm not against merging early, but I'm strongly against a process that will prevent additional feedback and comments from being adequately expressed and addressed https://github.com/scikit-learn/enhancement_proposals/pull/30#issuecomment-982519521.

The proposed workflow in this SLEP has limitations that have been voiced by multiple core devs (https://github.com/scikit-learn/enhancement_proposals/pull/30#issuecomment-982519521, https://github.com/scikit-learn/enhancement_proposals/pull/30#issuecomment-982946316, https://github.com/scikit-learn/enhancement_proposals/pull/30#issuecomment-994672509), but they are not addressed nor acknowledged in this SLEP proposal.

For these reasons I'm -1, sorry.

**Review by agramfort — APPROVED** [review]

**Review by jjerphan — APPROVED** [review]

**Review by lorentzenchr — APPROVED** [review]

**Review by glemaitre — APPROVED** [review]
I acknowledge that I am not 100% happy with the workflow proposed but I don't have a better proposal or counter-proposal at the time of the vote.

I give therefore my +1 hoping to provide some amendment in the future to improve the situation.

**Review by thomasjpfan — APPROVED** [review]

**Review by GaelVaroquaux — APPROVED** [review]
While I acknowledge that we could probably improve upon the details of this proposal, I believe that:
* It is a net improvement over what we currently have
* Good design is iterative and (unlike with some other SLEPs) we don't have a burden of backward compatibility here.

Hence I am +1 and approve. Thanks to everyone involved!

**Review by TomDLT — APPROVED** [review]
I find it a bit weird to accept a Process SLEP:
- that introduces explicitly "A Process SLEP describes a process surrounding scikit-learn [...]; they require community consensus." and that does not reach a consensus.
- that introduces explicitly a workflow for SLEPs (merge => follow-up discussions and reviews => vote), and that goes directly from merge to vote.

But I agree it is important to move forward (which is what this very SLEP aims to improve). Maybe we can mark this SLEP as "Provisional" ?

**Review by jnothman — APPROVED** [review]

**Comment by adrinjalali** [comment]
Counting the votes, it's 10 in favor (votes above plus myself), and one opposed. The vote satisfies 2/3 majority of cast votes. Therefore this motion (accepting SLEP000) is passed per our governance.

**Pull request merged**
